In [10]:
import pandas as pd

In [11]:
data = pd.read_csv("ks-projects-201801.csv")
data

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378656,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,2014-10-17,50000.0,2014-09-17 02:35:30,25.0,canceled,1,US,25.0,25.0,50000.00
378657,999977640,The Tribe,Narrative Film,Film & Video,USD,2011-07-19,1500.0,2011-06-22 03:35:14,155.0,failed,5,US,155.0,155.0,1500.00
378658,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,2010-08-16,15000.0,2010-07-01 19:40:30,20.0,failed,1,US,20.0,20.0,15000.00
378659,999987933,BioDefense Education Kit,Technology,Technology,USD,2016-02-13,15000.0,2016-01-13 18:13:53,200.0,failed,6,US,200.0,200.0,15000.00
378660,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2011-08-16,2000.0,2011-07-19 09:07:47,524.0,failed,17,US,524.0,524.0,2000.00

In [12]:
just3columns = data.filter(['category', 'state'])
just3columns

               category     state
0                Poetry    failed
1        Narrative Film    failed
2        Narrative Film    failed
3                 Music    failed
4          Film & Video  canceled
...                 ...       ...
378656      Documentary  canceled
378657   Narrative Film    failed
378658   Narrative Film    failed
378659       Technology    failed
378660  Performance Art    failed

[378661 rows x 2 columns]

In [13]:
unique_categories_in_array = just3columns.category.unique()
unique_categories_in_array

array(['Poetry', 'Narrative Film', 'Music', 'Film & Video', 'Restaurants',
       'Food', 'Drinks', 'Product Design', 'Documentary', 'Nonfiction',
       'Indie Rock', 'Crafts', 'Games', 'Tabletop Games', 'Design',
       'Comic Books', 'Art Books', 'Fashion', 'Childrenswear', 'Theater',
       'Comics', 'DIY', 'Webseries', 'Animation', 'Food Trucks',
       'Public Art', 'Illustration', 'Photography', 'Pop', 'People',
       'Art', 'Family', 'Fiction', 'Accessories', 'Rock', 'Hardware',
       'Software', 'Weaving', 'Gadgets', 'Web', 'Jazz', 'Ready-to-wear',
       'Festivals', 'Video Games', 'Anthologies', 'Publishing', 'Shorts',
       'Electronic Music', 'Radio & Podcasts', 'Apps', 'Cookbooks',
       'Apparel', 'Metal', 'Comedy', 'Hip-Hop', 'Periodicals', 'Dance',
       'Technology', 'Painting', 'World Music', 'Photobooks', 'Drama',
       'Architecture', 'Young Adult', 'Latin', 'Mobile Games', 'Flight',
       'Fine Art', 'Action', 'Playing Cards', 'Makerspaces', 'Punk',
       'Thrillers', "Children's Books", 'Audio', 'Performance Art',
       'Ceramics', 'Vegan', 'Graphic Novels', 'Fabrication Tools',
       'Performances', 'Sculpture', 'Sound', 'Stationery', 'Print',
       "Farmer's Markets", 'Events', 'Classical Music', 'Graphic Design',
       'Spaces', 'Country & Folk', 'Wearables', 'Mixed Media',
       'Journalism', 'Movie Theaters', 'Animals', 'Digital Art', 'Horror',
       'Knitting', 'Small Batch', 'Installations', 'Community Gardens',
       'DIY Electronics', 'Embroidery', 'Camera Equipment', 'Jewelry',
       'Farms', 'Conceptual Art', 'Fantasy', 'Webcomics', 'Experimental',
       'Science Fiction', 'Puzzles', 'R&B', 'Music Videos', 'Calendars',
       'Video', 'Plays', 'Blues', 'Bacon', 'Faith', 'Live Games',
       'Woodworking', 'Places', 'Footwear', '3D Printing', 'Academic',
       'Zines', 'Musical', 'Workshops', 'Photo', 'Immersive',
       'Letterpress', 'Gaming Hardware', 'Candles', 'Television',
       'Space Exploration', 'Couture', 'Nature', 'Robots', 'Typography',
       'Crochet', 'Translations', 'Textiles', 'Pottery',
       'Interactive Design', 'Video Art', 'Quilts', 'Glass',
       'Pet Fashion', 'Printing', 'Romance', 'Civic Design', 'Kids',
       'Literary Journals', 'Taxidermy', 'Literary Spaces', 'Chiptune',
       'Residencies'], dtype=object)

In [14]:
categories = 0
for category in unique_categories_in_array:
    categories += 1
print(categories)

159

In [15]:
filter_places = data.category.str.contains('Residencies', na=False)
data[filter_places].head(10) #fithers the list, shows only places with that category
#len(just3columns[filter_places]) #length of the filtered list

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
22912,1116274846,"Residencia en Guanajuato para ensayo de ""La Ca...",Residencies,Dance,MXN,2017-10-12,10000.0,2017-09-12 04:04:43,650.00,failed,4,MX,0.00,34.29,527.51
37001,1187694799,Cascade Youth Dance: Commonwealth,Residencies,Dance,GBP,2014-06-30,1000.0,2014-05-26 20:09:32,1170.00,successful,9,GB,1969.26,2005.79,1714.35
39991,1203401757,Plastic Identities,Residencies,Dance,USD,2017-07-20,6500.0,2017-06-20 23:07:41,7106.99,successful,85,US,543.00,7106.99,6500.00
49862,1254031717,Peter & Co. SF Presents at The Garage,Residencies,Dance,USD,2014-08-02,4500.0,2014-07-03 01:05:55,805.00,failed,24,US,805.00,805.00,4500.00
63571,1323294718,Turn my house into a ball pit party.,Residencies,Dance,CAD,2014-11-27,1000.0,2014-10-28 07:30:04,1.00,failed,1,CA,0.89,0.88,877.42
77308,1393285959,Eliot Smith Company at Paris Marais Dance School,Residencies,Dance,GBP,2015-06-07,1000.0,2015-04-29 19:12:18,100.00,failed,1,GB,152.29,154.87,1548.66
81250,1413234199,Primera Mexicana en ODI Orchidaceae Dance Inte...,Residencies,Dance,MXN,2017-05-02,37000.0,2017-03-03 19:36:28,37002.00,successful,30,MX,0.00,1941.75,1941.65
94952,1482611116,International Interdisciplinary Artists Consor...,Residencies,Dance,USD,2015-09-06,5000.0,2015-08-20 19:30:00,5026.00,successful,48,US,5026.00,5026.00,5000.00
95730,1486562048,Tyree (Robert) to danceWEB (and back),Residencies,Dance,USD,2011-05-30,3210.0,2011-05-14 01:29:09,3262.78,successful,61,US,3262.78,3262.78,3210.00
98741,1501259092,Moms Make Art Residency and Explicit Female pe...,Residencies,Dance,USD,2016-05-02,2391.0,2016-04-08 06:12:19,2454.52,successful,58,US,2454.52,2454.52,2391.00

In [16]:
#filters based on 'sucessful'
successful_filter = just3columns[filter_places].state.str.contains('successful')
#lenght of this filtered list
just3columns[filter_places][successful_filter]

           category       state
37001   Residencies  successful
39991   Residencies  successful
81250   Residencies  successful
94952   Residencies  successful
95730   Residencies  successful
98741   Residencies  successful
114380  Residencies  successful
124039  Residencies  successful
133179  Residencies  successful
136606  Residencies  successful
149616  Residencies  successful
154963  Residencies  successful
164102  Residencies  successful
181473  Residencies  successful
185284  Residencies  successful
196319  Residencies  successful
198469  Residencies  successful
203758  Residencies  successful
207029  Residencies  successful
209764  Residencies  successful
210821  Residencies  successful
218512  Residencies  successful
220803  Residencies  successful
233736  Residencies  successful
237468  Residencies  successful
243580  Residencies  successful
252688  Residencies  successful
259229  Residencies  successful
263636  Residencies  successful
263878  Residencies  successful
268194  Residencies  successful
273670  Residencies  successful
274608  Residencies  successful
283074  Residencies  successful
290011  Residencies  successful
295622  Residencies  successful
298362  Residencies  successful
298370  Residencies  successful
300295  Residencies  successful
301313  Residencies  successful
302587  Residencies  successful
316631  Residencies  successful
321600  Residencies  successful
328732  Residencies  successful
337737  Residencies  successful
352116  Residencies  successful
354470  Residencies  successful
366208  Residencies  successful
369507  Residencies  successful
375961  Residencies  successful

In [18]:
# ms = most_successful
ms_category = ""
ms_successes = 0
ms_attempts = 0
ms_rate = 0
#ls = least_successful
ls_category = ""
ls_successes = 0
ls_attempts = 0
ls_rate = 100

for category in unique_categories_in_array: #loops through all categories

    filter_category = just3columns.category.str.contains(f"{category}")
    projects_in_category = len(just3columns[filter_category]) # number of hits in category
    
    filter_success = just3columns[filter_category].state.str.contains('successful')
    successes_in_category = len(just3columns[filter_category][filter_success]) # successes in category
    
    success_rate = successes_in_category / projects_in_category
    if success_rate > ms_rate:
        ms_category = category
        ms_successes = successes_in_category
        ms_attempts = projects_in_category
        ms_rate = success_rate
        
    elif success_rate < ls_rate:
        ls_category = category
        ls_successes = successes_in_category
        ls_attempts = projects_in_category
        ls_rate = success_rate
  
print(f"The most successful category is {ms_category} with {ms_attempts}",
          f"attempts with {ms_successes} successes, with a success rate of {ms_rate}")
print(f"The least successful category is {ls_category} with {ls_attempts}",
          f"attempts with {ls_successes} successes, with a success rate of {ls_rate}")

The most successful category is Chiptune with 35 attempts with 27 successes, with a success rate of 0.7714285714285715
The least successful category is Apps with 6345 attempts with 378 successes, with a success rate of 0.059574468085106386

In [19]:
category_rankings = []

loops = 0

for category in unique_categories_in_array:
    
    #loops += 1
    #if loops > 10:
    #    break
        
    filter_category = just3columns.category.str.contains(f"{category}")
    projects_in_category = len(just3columns[filter_category]) # number of hits in category
    
    filter_success = just3columns[filter_category].state.str.contains('successful')
    successes_in_category = len(just3columns[filter_category][filter_success]) # successes in category
    
    success_rate = successes_in_category / projects_in_category
    
    new_category_data = {'category':category, 'successrate': success_rate, 'successes':successes_in_category, 'projects':projects_in_category}
    category_rankings.append(new_category_data)
    
    
#print(category_rankings)
    
#this point of the code works

newlist = sorted(category_rankings, key=lambda k: k['successrate'], reverse=True) 

ranking = 0
for category_data in newlist:
    ranking += 1
    print(f"{ranking}. {category_data['category']} with a success rate of {category_data['successrate']}.",
              f"with {category_data['successes']} from {category_data['projects']} attempts.")

1. Chiptune with a success rate of 0.7714285714285715. with 27 from 35 attempts.
2. Residencies with a success rate of 0.7246376811594203. with 50 from 69 attempts.
3. Anthologies with a success rate of 0.6645408163265306. with 521 from 784 attempts.
4. Dance with a success rate of 0.6640826873385013. with 1542 from 2322 attempts.
5. Indie Rock with a success rate of 0.6395616050910377. with 3618 from 5657 attempts.
6. Letterpress with a success rate of 0.6326530612244898. with 31 from 49 attempts.
7. Country & Folk with a success rate of 0.631768141990564. with 2812 from 4451 attempts.
8. Classical Music with a success rate of 0.6303099885189437. with 1647 from 2613 attempts.
9. Performances with a success rate of 0.6159921026653504. with 624 from 1013 attempts.
10. Theater with a success rate of 0.6114693373576622. with 4457 from 7289 attempts.
11. Jazz with a success rate of 0.5967567567567568. with 1104 from 1850 attempts.
12. Comic Books with a success rate of 0.5884068538096974. with 1614 from 2743 attempts.
13. Plays with a success rate of 0.5834542815674891. with 804 from 1378 attempts.
14. Typography with a success rate of 0.5833333333333334. with 63 from 108 attempts.
15. Rock with a success rate of 0.5733387031816352. with 7118 from 12415 attempts.
16. Tabletop Games with a success rate of 0.5547249647390691. with 7866 from 14180 attempts.
17. Webcomics with a success rate of 0.5524691358024691. with 358 from 648 attempts.
18. Festivals with a success rate of 0.5446960667461264. with 457 from 839 attempts.
19. Graphic Novels with a success rate of 0.5423819742489271. with 1011 from 1864 attempts.
20. Shorts with a success rate of 0.540017803674031. with 6673 from 12357 attempts.
21. Illustration with a success rate of 0.5121259842519685. with 1626 from 3175 attempts.
22. Immersive with a success rate of 0.5121212121212121. with 169 from 330 attempts.
23. Art Books with a success rate of 0.5067264573991032. with 1356 from 2676 attempts.
24. Musical with a success rate of 0.5060240963855421. with 462 from 913 attempts.
25. Comics with a success rate of 0.5016012810248198. with 2506 from 4996 attempts.
26. Public Art with a success rate of 0.501462463438414. with 1543 from 3077 attempts.
27. Installations with a success rate of 0.483402489626556. with 233 from 482 attempts.
28. Literary Spaces with a success rate of 0.48148148148148145. with 13 from 27 attempts.
29. Literary Journals with a success rate of 0.4784172661870504. with 133 from 278 attempts.
30. Knitting with a success rate of 0.4696132596685083. with 85 from 181 attempts.
31. Pop with a success rate of 0.46597014925373137. with 1561 from 3350 attempts.
32. DIY Electronics with a success rate of 0.4623059866962306. with 417 from 902 attempts.
33. Camera Equipment with a success rate of 0.46153846153846156. with 192 from 416 attempts.
34. Punk with a success rate of 0.4605678233438486. with 146 from 317 attempts.
35. Zines with a success rate of 0.4578005115089514. with 179 from 391 attempts.
36. Kids with a success rate of 0.4421052631578947. with 126 from 285 attempts.
37. Pottery with a success rate of 0.44. with 44 from 100 attempts.
38. World Music with a success rate of 0.4386298763082778. with 922 from 2102 attempts.
39. Blues with a success rate of 0.43656716417910446. with 117 from 268 attempts.
40. Performance Art with a success rate of 0.4336118848653668. with 934 from 2154 attempts.
41. Ceramics with a success rate of 0.43278688524590164. with 132 from 305 attempts.
42. Music with a success rate of 0.42927292234051334. with 10403 from 24234 attempts.
43. Radio & Podcasts with a success rate of 0.4268689057421452. with 394 from 923 attempts.
44. Art with a success rate of 0.4249461704091049. with 8289 from 19506 attempts.
45. Faith with a success rate of 0.4175824175824176. with 456 from 1092 attempts.
46. Sound with a success rate of 0.40956651718983555. with 274 from 669 attempts.
47. Periodicals with a success rate of 0.40711462450592883. with 515 from 1265 attempts.
48. Photobooks with a success rate of 0.40189873417721517. with 635 from 1580 attempts.
49. Robots with a success rate of 0.3951048951048951. with 226 from 572 attempts.
50. Comedy with a success rate of 0.3931034482758621. with 912 from 2320 attempts.
51. Calendars with a success rate of 0.3890577507598784. with 128 from 329 attempts.
52. Narrative Film with a success rate of 0.3880107941403238. with 2013 from 5188 attempts.
53. Experimental with a success rate of 0.3874458874458874. with 358 from 924 attempts.
54. Playing Cards with a success rate of 0.3872647176611934. with 967 from 2497 attempts.
55. Sculpture with a success rate of 0.3856353591160221. with 698 from 1810 attempts.
56. Taxidermy with a success rate of 0.38461538461538464. with 5 from 13 attempts.
57. Metal with a success rate of 0.38354253835425384. with 275 from 717 attempts.
58. Puzzles with a success rate of 0.38095238095238093. with 88 from 231 attempts.
59. Graphic Design with a success rate of 0.37462537462537465. with 750 from 2002 attempts.
60. Drama with a success rate of 0.3726480036714089. with 812 from 2179 attempts.
61. Space Exploration with a success rate of 0.3715170278637771. with 120 from 323 attempts.
62. Documentary with a success rate of 0.36706115620546503. with 5924 from 16139 attempts.
63. Science Fiction with a success rate of 0.3655913978494624. with 272 from 744 attempts.
64. Fine Art with a success rate of 0.3646907216494845. with 283 from 776 attempts.
65. Civic Design with a success rate of 0.35986159169550175. with 104 from 289 attempts.
66. Product Design with a success rate of 0.3568163484807744. with 7962 from 22314 attempts.
67. Poetry with a success rate of 0.3557341124908692. with 487 from 1369 attempts.
68. Conceptual Art with a success rate of 0.3553398058252427. with 366 from 1030 attempts.
69. Spaces with a success rate of 0.3548387096774194. with 308 from 868 attempts.
70. 3D Printing with a success rate of 0.35431918008784774. with 242 from 683 attempts.
71. Games with a success rate of 0.354294621979735. with 11364 from 32075 attempts.
72. Design with a success rate of 0.35298952126566674. with 10308 from 29202 attempts.
73. Stationery with a success rate of 0.3515981735159817. with 77 from 219 attempts.
74. Painting with a success rate of 0.348816029143898. with 1149 from 3294 attempts.
75. Children's Books with a success rate of 0.3475429248075784. with 2348 from 6756 attempts.
76. Mixed Media with a success rate of 0.34276387377584333. with 945 from 2757 attempts.
77. Accessories with a success rate of 0.3390205371248025. with 1073 from 3165 attempts.
78. Music Videos with a success rate of 0.3385049365303244. with 240 from 709 attempts.
79. Photo with a success rate of 0.3378055260361318. with 2543 from 7528 attempts.
80. Photography with a success rate of 0.32614742698191934. with 1876 from 5752 attempts.
81. Electronic Music with a success rate of 0.3225806451612903. with 700 from 2170 attempts.
82. Footwear with a success rate of 0.3200859291084855. with 298 from 931 attempts.
83. Makerspaces with a success rate of 0.31932773109243695. with 76 from 238 attempts.
84. Hardware with a success rate of 0.3189929112686385. with 1305 from 4091 attempts.
85. Printing with a success rate of 0.31596091205211724. with 291 from 921 attempts.
86. Wearables with a success rate of 0.3146796431467964. with 388 from 1233 attempts.
87. Vegan with a success rate of 0.31462585034013607. with 185 from 588 attempts.
88. Horror with a success rate of 0.3084693084693085. with 397 from 1287 attempts.
89. Small Batch with a success rate of 0.30807522123893805. with 557 from 1808 attempts.
90. Fantasy with a success rate of 0.3072463768115942. with 106 from 345 attempts.
91. Workshops with a success rate of 0.3048780487804878. with 50 from 164 attempts.
92. Film & Video with a success rate of 0.3037198258804907. with 3070 from 10108 attempts.
93. Webseries with a success rate of 0.2946893439777855. with 1698 from 5762 attempts.
94. Weaving with a success rate of 0.2903225806451613. with 27 from 93 attempts.
95. Romance with a success rate of 0.2894736842105263. with 55 from 190 attempts.
96. DIY with a success rate of 0.2891566265060241. with 600 from 2075 attempts.
97. Textiles with a success rate of 0.27898550724637683. with 77 from 276 attempts.
98. Gadgets with a success rate of 0.278920741989882. with 827 from 2965 attempts.
99. Latin with a success rate of 0.2773722627737226. with 38 from 137 attempts.
100. Digital Art with a success rate of 0.27563150074294207. with 371 from 1346 attempts.
101. Glass with a success rate of 0.2753623188405797. with 38 from 138 attempts.
102. Print with a success rate of 0.27427184466019416. with 452 from 1648 attempts.
103. Publishing with a success rate of 0.2725157859754071. with 1640 from 6018 attempts.
104. Audio with a success rate of 0.2707317073170732. with 111 from 410 attempts.
105. Journalism with a success rate of 0.2701774470520893. with 472 from 1747 attempts.
106. Animation with a success rate of 0.2683982683982684. with 682 from 2541 attempts.
107. Thrillers with a success rate of 0.2680965147453083. with 200 from 746 attempts.
108. Nonfiction with a success rate of 0.26809329165664825. with 2230 from 8318 attempts.
109. Pet Fashion with a success rate of 0.26618705035971224. with 37 from 139 attempts.
110. Food with a success rate of 0.26530766326915817. with 3514 from 13245 attempts.
111. Fabrication Tools with a success rate of 0.264. with 66 from 250 attempts.
112. Video Art with a success rate of 0.26288659793814434. with 51 from 194 attempts.
113. Fashion with a success rate of 0.25595306568503395. with 2225 from 8693 attempts.
114. Fiction with a success rate of 0.252698476747705. with 2505 from 9913 attempts.
115. Woodworking with a success rate of 0.25021422450728364. with 292 from 1167 attempts.
116. Video with a success rate of 0.24917271906828828. with 5798 from 23269 attempts.
117. Crafts with a success rate of 0.24914236706689538. with 1162 from 4664 attempts.
118. Animals with a success rate of 0.24705882352941178. with 63 from 255 attempts.
119. Drinks with a success rate of 0.24525185796862098. with 594 from 2422 attempts.
120. Jewelry with a success rate of 0.24293785310734464. with 301 from 1239 attempts.
121. Cookbooks with a success rate of 0.24074074074074073. with 130 from 540 attempts.
122. Architecture with a success rate of 0.2355263157894737. with 179 from 760 attempts.
123. Quilts with a success rate of 0.2345679012345679. with 19 from 81 attempts.
124. R&B with a success rate of 0.2336244541484716. with 107 from 458 attempts.
125. Gaming Hardware with a success rate of 0.23130841121495327. with 99 from 428 attempts.
126. Translations with a success rate of 0.22875816993464052. with 35 from 153 attempts.
127. Movie Theaters with a success rate of 0.22413793103448276. with 52 from 232 attempts.
128. Community Gardens with a success rate of 0.2214765100671141. with 66 from 298 attempts.
129. Web with a success rate of 0.2161203839833953. with 2499 from 11563 attempts.
130. Crochet with a success rate of 0.21604938271604937. with 35 from 162 attempts.
131. Farms with a success rate of 0.2097053726169844. with 242 from 1154 attempts.
132. Young Adult with a success rate of 0.2095006090133983. with 172 from 821 attempts.
133. People with a success rate of 0.2085222121486854. with 230 from 1103 attempts.
134. Academic with a success rate of 0.2052401746724891. with 188 from 916 attempts.
135. Video Games with a success rate of 0.20169061707523245. with 2386 from 11830 attempts.
136. Interactive Design with a success rate of 0.1984924623115578. with 79 from 398 attempts.
137. Apparel with a success rate of 0.1973206809935808. with 1414 from 7166 attempts.
138. Childrenswear with a success rate of 0.19668737060041408. with 95 from 483 attempts.
139. Family with a success rate of 0.19642857142857142. with 66 from 336 attempts.
140. Events with a success rate of 0.19315403422982885. with 158 from 818 attempts.
141. Technology with a success rate of 0.19004329004329004. with 1317 from 6930 attempts.
142. Flight with a success rate of 0.1784037558685446. with 76 from 426 attempts.
143. Nature with a success rate of 0.17421602787456447. with 100 from 574 attempts.
144. Bacon with a success rate of 0.17194570135746606. with 38 from 221 attempts.
145. Live Games with a success rate of 0.17142857142857143. with 180 from 1050 attempts.
146. Embroidery with a success rate of 0.168141592920354. with 19 from 113 attempts.
147. Ready-to-wear with a success rate of 0.16782407407407407. with 145 from 864 attempts.
148. Farmer's Markets with a success rate of 0.1650943396226415. with 70 from 424 attempts.
149. Restaurants with a success rate of 0.16211422490244767. with 457 from 2819 attempts.
150. Places with a success rate of 0.15967523680649526. with 118 from 739 attempts.
151. Hip-Hop with a success rate of 0.15388548057259713. with 602 from 3912 attempts.
152. Television with a success rate of 0.15369458128078817. with 156 from 1015 attempts.
153. Couture with a success rate of 0.15272727272727274. with 42 from 275 attempts.
154. Action with a success rate of 0.1445945945945946. with 107 from 740 attempts.
155. Candles with a success rate of 0.1282051282051282. with 55 from 429 attempts.
156. Food Trucks with a success rate of 0.12385844748858447. with 217 from 1752 attempts.
157. Software with a success rate of 0.12171916010498687. with 371 from 3048 attempts.
158. Mobile Games with a success rate of 0.08552263834544438. with 153 from 1789 attempts.
159. Apps with a success rate of 0.059574468085106386. with 378 from 6345 attempts.

In [20]:
d = {'one':1,'three':3,'five':5,'two':2,'four':4}
a = sorted(d.items(), key=lambda x: x[1])    
print(a)

[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)]