In [10]:
import pandas as pd

In [11]:
data = pd.read_csv("ks-projects-201801.csv")

In [21]:
result = data.sort_values(['category'], ascending=[0])

In [24]:
result.head(3)

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
64420,1327603481,Roameroo: Travel Mags and Plans,Zines,Publishing,USD,2014-08-11,33000.0,2014-07-09 18:49:19,6263.00,failed,14,US,6263.00,6263.00,33000.0
155090,1788711173,#Stock Tips: A Zine About Soup,Zines,Publishing,USD,2014-01-25,500.0,2014-01-14 21:38:55,6492.92,successful,730,US,6492.92,6492.92,500.0
158232,1804856616,SEDITION MAGAZINE,Zines,Publishing,USD,2016-07-18,2500.0,2016-07-08 22:05:03,2641.00,successful,38,US,424.00,2641.00,2500.0

In [28]:
namedata = data.sort_values('name', ascending=False).head(10)

In [29]:
namedata

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
103233,1524766221,€9 Universal Remote Control App for kid mum da...,Software,Technology,EUR,2015-06-26,19000.0,2015-05-27 09:28:38,0.0,failed,0,FR,0.00,0.00,21283.75
246541,323794635,‹Darf ich vorstellen? May I introduce?› Kinder...,Children's Books,Publishing,EUR,2017-07-08,4500.0,2017-06-08 23:46:25,1020.0,failed,33,DE,105.89,1164.33,5136.75
282515,507403134,••• New Music and Video Art ••• CD/DVD project...,Indie Rock,Music,USD,2010-12-13,2000.0,2010-09-14 23:47:54,2500.0,successful,54,US,2500.00,2500.00,2000.00
374346,977633355,•Tales of Terrene: Book One•,Video Games,Games,USD,2013-10-18,20000.0,2013-09-17 16:11:19,1942.0,failed,56,US,1942.00,1942.00,20000.00
9159,1046239660,•LiveJackets (Prototype 2),Wearables,Technology,GBP,2017-07-01,3000.0,2017-06-01 21:28:26,51.0,failed,3,GB,0.00,65.77,3869.02
47372,1241383071,• THE SHIFT • ( Film + Album ),Shorts,Film & Video,USD,2012-12-19,3000.0,2012-11-19 16:35:01,3180.0,successful,38,US,3180.00,3180.00,3000.00
201104,2024003408,• Rooftop •,Shorts,Film & Video,USD,2015-01-21,6500.0,2014-12-22 02:13:55,7896.0,successful,124,US,7896.00,7896.00,6500.00
158471,1806114726,• My first dream short film • Mon premier cour...,Film & Video,Film & Video,EUR,2015-07-19,1250.0,2015-06-28 03:36:34,0.0,undefined,0,"N,0""",NaN,0.00,1367.38
56976,1289892447,• Greenfinit •,Product Design,Design,USD,2013-11-29,70000.0,2013-10-25 20:01:21,19115.0,failed,98,US,19115.00,19115.00,70000.00
370412,957338579,•\tHelp save the honeybees: Provide funding to...,Food,Food,USD,2012-01-08,1875.0,2011-11-09 05:14:50,545.0,failed,13,US,545.00,545.00,1875.00